name: renovate-resolved

on:
  push:
    branches: [ "renovate/**" ]
    paths:
      - "AppleDocumentationPackage/Package.swift"

jobs:
  mac-os:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Update Package.resolved
        run: |
          cd AppleDocumentationPackage
          cp -f ../apple-documentation-package/project.xcworkspace/xcshareddata/swiftpm/Package.resolved Package.resolved
          swift package resolve
          cp -f Package.resolved ../apple-documentation-package/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
