name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_run:
    workflows: [renovate-resolved]
    types:
      - completed
  workflow_dispatch:

jobs:
  mac-os:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Make project
        run: make project
      - name: Run tests
        run: make unittest
